### PR TITLE
Add pytest framework

### PR DESCRIPTION
**Pull request by tkell**
Hello hello,

This PR updates the tests to use PyTest, (which I hope is what issue #6 meant).  You can run tests by running `pytest`!

Specifically, the PR:
- rewrites the credentials call to not use global variables.
- rewrites the test script to use PyTest
- lints stuff with PyLint
- renames `knack-load` to `knackload`
- adds `__init__` files
- adds docstrings
- Updates README.md with new testing info

Let me know what you think!

### CODE REVIEW

**Comment by dryan** [comment]
.pyc should definitely be in gitignore

**Comment by tkell** [comment]
Erk, beg pardon, assumed that I had `*.pyc` in a global gitignore.  Fixed!

**Comment by tkell** [comment]
@jillh510, added `object_id` back to the environment, in its own function.  Also made the URL a constant, as hopefully Knack does not change it very much.  

In terms of more-real test data, I saw your monster JSON file in Slack.  How concerned should we be with validating the data from ActBlue? (e.g. ZIP code as an integer vs a string)

**Comment by kcraybould** [comment]
@tkell   One of the reasons the testing was so limited initially was that I did not have much information about the Knack data when I did the work (I probably should have lest the test out of the PR.  I included it out of habit).  FWIW, I think we should be validating the data from ActBlue; I have to assume that the Knack data is or could be used in Knack applications and having it wrong would 1) prevent it form loading or, more importantly 2) potentially have unintended consequences downstream.

**Pull request merged**
